apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: halibut-go 
  janus-idp.io/tekton: halibut-go
  backstage.io/kubernetes-id: halibut-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: halibut-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  